return {
    swamptrees = {
        prefab_name = "swamptree",
        tree_tag = "swamptree",
        anim_bank = "tree_leaf",
        anim_build = "tree_leaf_trunk_build",
        assets = {
            Asset("ANIM", "anim/tree_leaf_short.zip"),
            Asset("ANIM", "anim/tree_leaf_normal.zip"),
            Asset("ANIM", "anim/tree_leaf_tall.zip"),
            Asset("ANIM", "anim/tree_leaf_monster.zip"),
            Asset("ANIM", "anim/tree_leaf_trunk_build.zip"),
            Asset("ANIM", "anim/tree_leaf_green_build.zip"),
            Asset("ANIM", "anim/tree_leaf_red_build.zip"),
            Asset("ANIM", "anim/tree_leaf_orange_build.zip"),
            Asset("ANIM", "anim/tree_leaf_yellow_build.zip"),
            Asset("ANIM", "anim/tree_leaf_poison_build.zip"),
            Asset("SOUND", "sound/forest.fsb"),
            Asset("SOUND", "sound/deciduous.fsb"),
            Asset("MINIMAP_IMAGE", "tree_leaf"),
            Asset("MINIMAP_IMAGE", "tree_leaf_burnt"),
            Asset("MINIMAP_IMAGE", "tree_leaf_stump"),
        },
    },
    savannatrees = {
        prefab_name = "savannatree",
        tree_tag = "savannatree",
        anim_bank = "jungletree",
        anim_build = "tree_jungle_build",
        hue = .85,
        assets = {
            Asset("ANIM", "anim/tree_jungle_build.zip"),
            Asset("ANIM", "anim/tree_jungle_normal.zip"),
            Asset("ANIM", "anim/tree_jungle_short.zip"),
            Asset("ANIM", "anim/tree_jungle_tall.zip"),
            Asset("SOUND", "sound/forest.fsb"),
            Asset("SOUND", "sound/deciduous.fsb"),
            Asset("MINIMAP_IMAGE", "tree_leaf"),
            Asset("MINIMAP_IMAGE", "tree_leaf_burnt"),
            Asset("MINIMAP_IMAGE", "tree_leaf_stump"),
        },
    },
    cactustrees = {
        prefab_name = "cactustree",
        tree_tag = "cactustree",
        anim_bank = "tubertree",
        anim_build = "tuber_tree_build",
        stages = {"short", "tall"},
        make_monster = false,
        hue = .85,
        assets = {
            Asset("ANIM", "anim/tuber_tree_build.zip"),
            Asset("ANIM", "anim/tuber_tree.zip"),
            Asset("SOUND", "sound/forest.fsb"),
        },
    }
}
