local seg_time = 30
local total_day_time = seg_time*16

local day_segs = 10
local dusk_segs = 4
local night_segs = 2

--default day composition. changes in winter, etc
local day_time = seg_time * day_segs
local dusk_time = seg_time * dusk_segs
local night_time = seg_time * night_segs

GLOBAL.CORDYCEPS_DISTANCE = 2.5

local REFRESH_TUNING = {
	MOSQUITOSWARM = {
		SMALL = {
			HEALTH = 50,
			SCALE = 0.5,
			SPEEDDOWN = 0.9,
			
			PERIOD = 15,
			DMG = 1,
		},
		
		MEDIUM = {
			HEALTH = 100,
			SCALE = 0.75,
			SPEEDDOWN = 0.75,
			
			PERIOD = 15,
			DMG = 2,
		},
		
		NORMAL = {
			HEALTH = 200,
			SCALE = 1,
			SPEEDDOWN = 0.5,
			
			PERIOD = 10,
			DMG = 3
		},
	},

	MOSQUITOSWARM_GROWTH = {
		OFFSPRING_TIME = total_day_time * 5,
		DESOLATION_RESPAWN_TIME = total_day_time * 50,
		DEAD_DECAY_TIME = total_day_time * 30,
	},

	MOSQUITOSWARM_COCOON_GROW_TIME =
	{
		{base=1.5*day_time, random=0.5*day_time},   --short
		{base=5*day_time, random=2*day_time},   --normal
		{base=5*day_time, random=2*day_time},   --tall
		{base=1*day_time, random=0.5*day_time}   --old
	},

	MOSQUITOSWARM_RESTOCK = 15,

	FUMEAGATOR_TARGETRANGE = 12,
	FUMEAGATOR_DAMAGE = 50,
	FUMEAGATOR_HEALTH = 1200,
	FUMEAGATOR_ATTACKRANGE = 5.5,
	FUMEAGATOR_ATTACKPERIOD = 2.5,
	FUMEAGATOR_FUMEPERIOD = 20,

	SHROOMBRELLA = {
		PRESERVER = {
			0.75,
			0.5,
			0.25,
			1,
		}
	},

	GIANTTREE_HP = 100000,
	GIANTTREE_DAMAGE = 60,
	GIANTTREE_ATTACK_RANGE = 5,

	GIANTTREE_STAGE2_PCT = 0.75,
	GIANTTREE_STAGE3_PCT = 0.50,
	GIANTTREE_STAGE4_PCT = 0.25,

	GIANTTREE_ROOT_CD_S1 = 15,
	GIANTTREE_ROOT_CD_S3 = 8,
	GIANTTREE_ROOT_SPAWN_RADIUS = 3,

	GIANTTREE_MOSQUITO_CD_S2 = 20,
	GIANTTREE_MOSQUITO_CD_S3 = 10,
	GIANTTREE_MOSQUITO_COUNT = 3,
	GIANTTREE_MOSQUITO_RADIUS = 10,

	GIANTTREE_REGEN_CD = 5,
	GIANTTREE_REGEN_IDLE_WINDOW = 8,
	GIANTTREE_REGEN_AMOUNT = 200,

	GIANTTREE_VINE_CD = 25,
	GIANTTREE_VINE_RANGE = 6,
	GIANTTREE_VINE_HOLD_TIME = 3,

	GIANTTREE_SEED_CD_S4 = 12,
	GIANTTREE_SEED_COUNT = 4,
	GIANTTREE_SEED_RADIUS = 10,
	GIANTTREE_SEED_HEIGHT = 15,

	ANCIENTDWELLER_HP = 10000,
	ANCIENTDWELLER_DAMAGE_BODY = 120,
	ANCIENTDWELLER_DAMAGE_LEG = 80,
	ANCIENTDWELLER_SPEED = 8,

	ANCIENTDWELLER_STAGE2_PCT = 0.75,
	ANCIENTDWELLER_STAGE3_PCT = 0.50,
	ANCIENTDWELLER_STAGE4_PCT = 0.25,

	ANCIENTDWELLER_LEG_SLAM_CD = 10,
	ANCIENTDWELLER_HEAD_SLAM_RANGE = 6,
	ANCIENTDWELLER_HEAD_SLAM_CD = 8,

	ANCIENTDWELLER_LEG_SLAM_DOUBLE_CD = 8,
	ANCIENTDWELLER_LEG_RETALIATE_RANGE = 5,

	ANCIENTDWELLER_CEILING_PHASE_CD = 30,
	ANCIENTDWELLER_CEILING_SPIDERS = 4,
	ANCIENTDWELLER_CEILING_BOMBS = 5,

	ANCIENTDWELLER_STOMP_CIRCLE_CD = 20,
	ANCIENTDWELLER_STOMP_NUM_DIRS = 8,
	ANCIENTDWELLER_STOMP_RINGS = 2,
	ANCIENTDWELLER_STOMP_RADIUS_STEP = 3,

	ANCIENTDWELLER_KNOCKED_OFF_CHANCE = 0.15,
	ANCIENTDWELLER_KNOCKED_OFF_SPIDERS = 6,
	ANCIENTDWELLER_LEG_RADIUS_S4_MULT = 0.75,

	ANCIENTDWELLER_FREEZE_IMMOBILE_COUNT = 3,
	ANCIENTDWELLER_FREEZE_FORCE_THAW_COUNT = 2,

	ANCIENTDWELLER_SPAWN_LEG1_DELAY = 0,
	ANCIENTDWELLER_SPAWN_LEG2_DELAY = 1,
	ANCIENTDWELLER_SPAWN_LEGS34_DELAY = 2,
	ANCIENTDWELLER_SPAWN_LEGS5678_DELAY = 4,
}

for key, value in pairs(REFRESH_TUNING) do
    TUNING[key] = value
end
